// via https://theunderminejournal.com/#us and https://theunderminejournal.com/#eu respectively
export const realms = [
    { slug: "aegwynn", name: "Aegwynn", region: "eu" },
    { slug: "aerie-peak", name: "Aerie Peak", region: "eu" },
    { slug: "agamaggan", name: "Agamaggan", region: "eu" },
    { slug: "aggra-portugu%C3%AAs", name: "Aggra (Português)", region: "eu" },
    { slug: "aggramar", name: "Aggramar", region: "eu" },
    { slug: "ahnqiraj", name: "Ahn'Qiraj", region: "eu" },
    { slug: "alakir", name: "Al'Akir", region: "eu" },
    { slug: "alexstrasza", name: "Alexstrasza", region: "eu" },
    { slug: "alleria", name: "Alleria", region: "eu" },
    { slug: "alonsus", name: "Alonsus", region: "eu" },
    { slug: "amanthul", name: "Aman'Thul", region: "eu" },
    { slug: "ambossar", name: "Ambossar", region: "eu" },
    { slug: "anachronos", name: "Anachronos", region: "eu" },
    { slug: "anetheron", name: "Anetheron", region: "eu" },
    { slug: "antonidas", name: "Antonidas", region: "eu" },
    { slug: "anubarak", name: "Anub'arak", region: "eu" },
    { slug: "arakarahm", name: "Arak-arahm", region: "eu" },
    { slug: "arathi", name: "Arathi", region: "eu" },
    { slug: "arathor", name: "Arathor", region: "eu" },
    { slug: "archimonde", name: "Archimonde", region: "eu" },
    { slug: "area-52", name: "Area 52", region: "eu" },
    { slug: "argent-dawn", name: "Argent Dawn", region: "eu" },
    { slug: "arthas", name: "Arthas", region: "eu" },
    { slug: "arygos", name: "Arygos", region: "eu" },
    { slug: "ashenvale", name: "Ashenvale", region: "eu" },
    { slug: "aszune", name: "Aszune", region: "eu" },
    { slug: "auchindoun", name: "Auchindoun", region: "eu" },
    { slug: "azjolnerub", name: "Azjol-Nerub", region: "eu" },
    { slug: "azshara", name: "Azshara", region: "eu" },
    { slug: "azuregos", name: "Azuregos", region: "eu" },
    { slug: "azuremyst", name: "Azuremyst", region: "eu" },
    { slug: "baelgun", name: "Baelgun", region: "eu" },
    { slug: "balnazzar", name: "Balnazzar", region: "eu" },
    { slug: "blackhand", name: "Blackhand", region: "eu" },
    { slug: "blackmoore", name: "Blackmoore", region: "eu" },
    { slug: "blackrock", name: "Blackrock", region: "eu" },
    { slug: "blackscar", name: "Blackscar", region: "eu" },
    { slug: "blades-edge", name: "Blade's Edge", region: "eu" },
    { slug: "bladefist", name: "Bladefist", region: "eu" },
    { slug: "bloodfeather", name: "Bloodfeather", region: "eu" },
    { slug: "bloodhoof", name: "Bloodhoof", region: "eu" },
    { slug: "bloodscalp", name: "Bloodscalp", region: "eu" },
    { slug: "blutkessel", name: "Blutkessel", region: "eu" },
    { slug: "booty-bay", name: "Booty Bay", region: "eu" },
    { slug: "borean-tundra", name: "Borean Tundra", region: "eu" },
    { slug: "boulderfist", name: "Boulderfist", region: "eu" },
    { slug: "bronze-dragonflight", name: "Bronze Dragonflight", region: "eu" },
    { slug: "bronzebeard", name: "Bronzebeard", region: "eu" },
    { slug: "burning-blade", name: "Burning Blade", region: "eu" },
    { slug: "burning-legion", name: "Burning Legion", region: "eu" },
    { slug: "burning-steppes", name: "Burning Steppes", region: "eu" },
    { slug: "cthun", name: "C'Thun", region: "eu" },
    { slug: "chamber-of-aspects", name: "Chamber of Aspects", region: "eu" },
    { slug: "chants-%C3%A9ternels", name: "Chants éternels", region: "eu" },
    { slug: "chogall", name: "Cho'gall", region: "eu" },
    { slug: "chromaggus", name: "Chromaggus", region: "eu" },
    { slug: "colinas-pardas", name: "Colinas Pardas", region: "eu" },
    {
        slug: "confr%C3%A9rie-du-thorium",
        name: "Confrérie du Thorium",
        region: "eu",
    },
    { slug: "conseil-des-ombres", name: "Conseil des Ombres", region: "eu" },
    { slug: "crushridge", name: "Crushridge", region: "eu" },
    {
        slug: "culte-de-la-rive-noire",
        name: "Culte de la Rive noire",
        region: "eu",
    },
    { slug: "daggerspine", name: "Daggerspine", region: "eu" },
    { slug: "dalaran", name: "Dalaran", region: "eu" },
    { slug: "dalvengyr", name: "Dalvengyr", region: "eu" },
    { slug: "darkmoon-faire", name: "Darkmoon Faire", region: "eu" },
    { slug: "darksorrow", name: "Darksorrow", region: "eu" },
    { slug: "darkspear", name: "Darkspear", region: "eu" },
    { slug: "das-konsortium", name: "Das Konsortium", region: "eu" },
    { slug: "das-syndikat", name: "Das Syndikat", region: "eu" },
    { slug: "deathguard", name: "Deathguard", region: "eu" },
    { slug: "deathweaver", name: "Deathweaver", region: "eu" },
    { slug: "deathwing", name: "Deathwing", region: "eu" },
    { slug: "deepholm", name: "Deepholm", region: "eu" },
    { slug: "defias-brotherhood", name: "Defias Brotherhood", region: "eu" },
    { slug: "dentarg", name: "Dentarg", region: "eu" },
    { slug: "der-abyssische-rat", name: "Der abyssische Rat", region: "eu" },
    { slug: "der-mithrilorden", name: "Der Mithrilorden", region: "eu" },
    { slug: "der-rat-von-dalaran", name: "Der Rat von Dalaran", region: "eu" },
    { slug: "destromath", name: "Destromath", region: "eu" },
    { slug: "dethecus", name: "Dethecus", region: "eu" },
    { slug: "die-aldor", name: "Die Aldor", region: "eu" },
    { slug: "die-arguswacht", name: "Die Arguswacht", region: "eu" },
    { slug: "die-ewige-wacht", name: "Die ewige Wacht", region: "eu" },
    { slug: "die-nachtwache", name: "Die Nachtwache", region: "eu" },
    { slug: "die-silberne-hand", name: "Die Silberne Hand", region: "eu" },
    { slug: "die-todeskrallen", name: "Die Todeskrallen", region: "eu" },
    { slug: "doomhammer", name: "Doomhammer", region: "eu" },
    { slug: "draenor", name: "Draenor", region: "eu" },
    { slug: "dragonblight", name: "Dragonblight", region: "eu" },
    { slug: "dragonmaw", name: "Dragonmaw", region: "eu" },
    { slug: "drakthul", name: "Drak'thul", region: "eu" },
    { slug: "drekthar", name: "Drek'Thar", region: "eu" },
    { slug: "dun-modr", name: "Dun Modr", region: "eu" },
    { slug: "dun-morogh", name: "Dun Morogh", region: "eu" },
    { slug: "dunemaul", name: "Dunemaul", region: "eu" },
    { slug: "durotan", name: "Durotan", region: "eu" },
    { slug: "earthen-ring", name: "Earthen Ring", region: "eu" },
    { slug: "echsenkessel", name: "Echsenkessel", region: "eu" },
    { slug: "eitrigg", name: "Eitrigg", region: "eu" },
    { slug: "eldrethalas", name: "Eldre'Thalas", region: "eu" },
    { slug: "elune", name: "Elune", region: "eu" },
    { slug: "emerald-dream", name: "Emerald Dream", region: "eu" },
    { slug: "emeriss", name: "Emeriss", region: "eu" },
    { slug: "eonar", name: "Eonar", region: "eu" },
    { slug: "eredar", name: "Eredar", region: "eu" },
    { slug: "eversong", name: "Eversong", region: "eu" },
    { slug: "executus", name: "Executus", region: "eu" },
    { slug: "exodar", name: "Exodar", region: "eu" },
    {
        slug: "festung-der-st%C3%BCrme",
        name: "Festung der Stürme",
        region: "eu",
    },
    { slug: "fordragon", name: "Fordragon", region: "eu" },
    { slug: "forscherliga", name: "Forscherliga", region: "eu" },
    { slug: "frostmane", name: "Frostmane", region: "eu" },
    { slug: "frostmourne", name: "Frostmourne", region: "eu" },
    { slug: "frostwhisper", name: "Frostwhisper", region: "eu" },
    { slug: "frostwolf", name: "Frostwolf", region: "eu" },
    { slug: "galakrond", name: "Galakrond", region: "eu" },
    { slug: "garona", name: "Garona", region: "eu" },
    { slug: "garrosh", name: "Garrosh", region: "eu" },
    { slug: "genjuros", name: "Genjuros", region: "eu" },
    { slug: "ghostlands", name: "Ghostlands", region: "eu" },
    { slug: "gilneas", name: "Gilneas", region: "eu" },
    { slug: "goldrinn", name: "Goldrinn", region: "eu" },
    { slug: "gordunni", name: "Gordunni", region: "eu" },
    { slug: "gorgonnash", name: "Gorgonnash", region: "eu" },
    { slug: "greymane", name: "Greymane", region: "eu" },
    { slug: "grim-batol", name: "Grim Batol", region: "eu" },
    { slug: "grom", name: "Grom", region: "eu" },
    { slug: "guldan", name: "Gul'dan", region: "eu" },
    { slug: "hakkar", name: "Hakkar", region: "eu" },
    { slug: "haomarush", name: "Haomarush", region: "eu" },
    { slug: "hellfire", name: "Hellfire", region: "eu" },
    { slug: "hellscream", name: "Hellscream", region: "eu" },
    { slug: "howling-fjord", name: "Howling Fjord", region: "eu" },
    { slug: "hyjal", name: "Hyjal", region: "eu" },
    { slug: "illidan", name: "Illidan", region: "eu" },
    { slug: "jaedenar", name: "Jaedenar", region: "eu" },
    { slug: "kaelthas", name: "Kael'thas", region: "eu" },
    { slug: "karazhan", name: "Karazhan", region: "eu" },
    { slug: "kargath", name: "Kargath", region: "eu" },
    { slug: "kazzak", name: "Kazzak", region: "eu" },
    { slug: "kelthuzad", name: "Kel'Thuzad", region: "eu" },
    { slug: "khadgar", name: "Khadgar", region: "eu" },
    { slug: "khaz-modan", name: "Khaz Modan", region: "eu" },
    { slug: "khazgoroth", name: "Khaz'goroth", region: "eu" },
    { slug: "kiljaeden", name: "Kil'jaeden", region: "eu" },
    { slug: "kilrogg", name: "Kilrogg", region: "eu" },
    { slug: "kirin-tor", name: "Kirin Tor", region: "eu" },
    { slug: "korgall", name: "Kor'gall", region: "eu" },
    { slug: "kragjin", name: "Krag'jin", region: "eu" },
    { slug: "krasus", name: "Krasus", region: "eu" },
    { slug: "kul-tiras", name: "Kul Tiras", region: "eu" },
    { slug: "kult-der-verdammten", name: "Kult der Verdammten", region: "eu" },
    {
        slug: "la-croisade-%C3%A9carlate",
        name: "La Croisade écarlate",
        region: "eu",
    },
    { slug: "laughing-skull", name: "Laughing Skull", region: "eu" },
    { slug: "les-clairvoyants", name: "Les Clairvoyants", region: "eu" },
    { slug: "les-sentinelles", name: "Les Sentinelles", region: "eu" },
    { slug: "lich-king", name: "Lich King", region: "eu" },
    { slug: "lightbringer", name: "Lightbringer", region: "eu" },
    { slug: "lightnings-blade", name: "Lightning's Blade", region: "eu" },
    { slug: "lordaeron", name: "Lordaeron", region: "eu" },
    { slug: "los-errantes", name: "Los Errantes", region: "eu" },
    { slug: "lothar", name: "Lothar", region: "eu" },
    { slug: "madmortem", name: "Madmortem", region: "eu" },
    { slug: "magtheridon", name: "Magtheridon", region: "eu" },
    { slug: "malganis", name: "Mal'Ganis", region: "eu" },
    { slug: "malfurion", name: "Malfurion", region: "eu" },
    { slug: "malorne", name: "Malorne", region: "eu" },
    { slug: "malygos", name: "Malygos", region: "eu" },
    { slug: "mannoroth", name: "Mannoroth", region: "eu" },
    {
        slug: "mar%C3%A9cage-de-zangar",
        name: "Marécage de Zangar",
        region: "eu",
    },
    { slug: "mazrigos", name: "Mazrigos", region: "eu" },
    { slug: "medivh", name: "Medivh", region: "eu" },
    { slug: "minahonda", name: "Minahonda", region: "eu" },
    { slug: "moonglade", name: "Moonglade", region: "eu" },
    { slug: "mugthol", name: "Mug'thol", region: "eu" },
    { slug: "nagrand", name: "Nagrand", region: "eu" },
    { slug: "nathrezim", name: "Nathrezim", region: "eu" },
    { slug: "naxxramas", name: "Naxxramas", region: "eu" },
    { slug: "nazjatar", name: "Nazjatar", region: "eu" },
    { slug: "nefarian", name: "Nefarian", region: "eu" },
    { slug: "nemesis", name: "Nemesis", region: "eu" },
    { slug: "neptulon", name: "Neptulon", region: "eu" },
    { slug: "nerzhul", name: "Ner'zhul", region: "eu" },
    { slug: "nerathor", name: "Nera'thor", region: "eu" },
    { slug: "nethersturm", name: "Nethersturm", region: "eu" },
    { slug: "nordrassil", name: "Nordrassil", region: "eu" },
    { slug: "norgannon", name: "Norgannon", region: "eu" },
    { slug: "nozdormu", name: "Nozdormu", region: "eu" },
    { slug: "onyxia", name: "Onyxia", region: "eu" },
    { slug: "outland", name: "Outland", region: "eu" },
    { slug: "perenolde", name: "Perenolde", region: "eu" },
    {
        slug: "pozzo-delleternit%C3%A0",
        name: "Pozzo dell'Eternità",
        region: "eu",
    },
    { slug: "proudmoore", name: "Proudmoore", region: "eu" },
    { slug: "quelthalas", name: "Quel'Thalas", region: "eu" },
    { slug: "ragnaros", name: "Ragnaros", region: "eu" },
    { slug: "rajaxx", name: "Rajaxx", region: "eu" },
    { slug: "rashgarroth", name: "Rashgarroth", region: "eu" },
    { slug: "ravencrest", name: "Ravencrest", region: "eu" },
    { slug: "ravenholdt", name: "Ravenholdt", region: "eu" },
    { slug: "razuvious", name: "Razuvious", region: "eu" },
    { slug: "rexxar", name: "Rexxar", region: "eu" },
    { slug: "runetotem", name: "Runetotem", region: "eu" },
    { slug: "sanguino", name: "Sanguino", region: "eu" },
    { slug: "sargeras", name: "Sargeras", region: "eu" },
    { slug: "saurfang", name: "Saurfang", region: "eu" },
    { slug: "scarshield-legion", name: "Scarshield Legion", region: "eu" },
    { slug: "senjin", name: "Sen'jin", region: "eu" },
    { slug: "shadowsong", name: "Shadowsong", region: "eu" },
    { slug: "shattered-halls", name: "Shattered Halls", region: "eu" },
    { slug: "shattered-hand", name: "Shattered Hand", region: "eu" },
    { slug: "shattrath", name: "Shattrath", region: "eu" },
    { slug: "shendralar", name: "Shen'dralar", region: "eu" },
    { slug: "silvermoon", name: "Silvermoon", region: "eu" },
    { slug: "sinstralis", name: "Sinstralis", region: "eu" },
    { slug: "skullcrusher", name: "Skullcrusher", region: "eu" },
    { slug: "soulflayer", name: "Soulflayer", region: "eu" },
    { slug: "spinebreaker", name: "Spinebreaker", region: "eu" },
    { slug: "sporeggar", name: "Sporeggar", region: "eu" },
    { slug: "steamwheedle-cartel", name: "Steamwheedle Cartel", region: "eu" },
    { slug: "stormrage", name: "Stormrage", region: "eu" },
    { slug: "stormreaver", name: "Stormreaver", region: "eu" },
    { slug: "stormscale", name: "Stormscale", region: "eu" },
    { slug: "sunstrider", name: "Sunstrider", region: "eu" },
    { slug: "suramar", name: "Suramar", region: "eu" },
    { slug: "sylvanas", name: "Sylvanas", region: "eu" },
    { slug: "taerar", name: "Taerar", region: "eu" },
    { slug: "talnivarr", name: "Talnivarr", region: "eu" },
    { slug: "tarren-mill", name: "Tarren Mill", region: "eu" },
    { slug: "teldrassil", name: "Teldrassil", region: "eu" },
    { slug: "temple-noir", name: "Temple noir", region: "eu" },
    { slug: "terenas", name: "Terenas", region: "eu" },
    { slug: "terokkar", name: "Terokkar", region: "eu" },
    { slug: "terrordar", name: "Terrordar", region: "eu" },
    { slug: "the-maelstrom", name: "The Maelstrom", region: "eu" },
    { slug: "the-shatar", name: "The Sha'tar", region: "eu" },
    { slug: "the-venture-co", name: "The Venture Co", region: "eu" },
    { slug: "theradras", name: "Theradras", region: "eu" },
    { slug: "thermaplugg", name: "Thermaplugg", region: "eu" },
    { slug: "thrall", name: "Thrall", region: "eu" },
    { slug: "throkferoth", name: "Throk'Feroth", region: "eu" },
    { slug: "thunderhorn", name: "Thunderhorn", region: "eu" },
    { slug: "tichondrius", name: "Tichondrius", region: "eu" },
    { slug: "tirion", name: "Tirion", region: "eu" },
    { slug: "todeswache", name: "Todeswache", region: "eu" },
    { slug: "trollbane", name: "Trollbane", region: "eu" },
    { slug: "turalyon", name: "Turalyon", region: "eu" },
    { slug: "twilights-hammer", name: "Twilight's Hammer", region: "eu" },
    { slug: "twisting-nether", name: "Twisting Nether", region: "eu" },
    { slug: "tyrande", name: "Tyrande", region: "eu" },
    { slug: "uldaman", name: "Uldaman", region: "eu" },
    { slug: "ulduar", name: "Ulduar", region: "eu" },
    { slug: "uldum", name: "Uldum", region: "eu" },
    { slug: "ungoro", name: "Un'Goro", region: "eu" },
    { slug: "varimathras", name: "Varimathras", region: "eu" },
    { slug: "vashj", name: "Vashj", region: "eu" },
    { slug: "veklor", name: "Vek'lor", region: "eu" },
    { slug: "veknilash", name: "Vek'nilash", region: "eu" },
    { slug: "voljin", name: "Vol'jin", region: "eu" },
    { slug: "wildhammer", name: "Wildhammer", region: "eu" },
    { slug: "wrathbringer", name: "Wrathbringer", region: "eu" },
    { slug: "xavius", name: "Xavius", region: "eu" },
    { slug: "ysera", name: "Ysera", region: "eu" },
    { slug: "ysondre", name: "Ysondre", region: "eu" },
    { slug: "zenedar", name: "Zenedar", region: "eu" },
    { slug: "zirkel-des-cenarius", name: "Zirkel des Cenarius", region: "eu" },
    { slug: "zuljin", name: "Zul'jin", region: "eu" },
    { slug: "zuluhed", name: "Zuluhed", region: "eu" },

    { slug: "aegwynn", name: "Aegwynn", region: "us" },
    { slug: "aerie-peak", name: "Aerie Peak", region: "us" },
    { slug: "agamaggan", name: "Agamaggan", region: "us" },
    { slug: "aggramar", name: "Aggramar", region: "us" },
    { slug: "akama", name: "Akama", region: "us" },
    { slug: "alexstrasza", name: "Alexstrasza", region: "us" },
    { slug: "alleria", name: "Alleria", region: "us" },
    { slug: "altar-of-storms", name: "Altar of Storms", region: "us" },
    { slug: "alterac-mountains", name: "Alterac Mountains", region: "us" },
    { slug: "amanthul", name: "Aman'Thul", region: "us" },
    { slug: "andorhal", name: "Andorhal", region: "us" },
    { slug: "anetheron", name: "Anetheron", region: "us" },
    { slug: "antonidas", name: "Antonidas", region: "us" },
    { slug: "anubarak", name: "Anub'arak", region: "us" },
    { slug: "anvilmar", name: "Anvilmar", region: "us" },
    { slug: "arathor", name: "Arathor", region: "us" },
    { slug: "archimonde", name: "Archimonde", region: "us" },
    { slug: "area-52", name: "Area 52", region: "us" },
    { slug: "argent-dawn", name: "Argent Dawn", region: "us" },
    { slug: "arthas", name: "Arthas", region: "us" },
    { slug: "arygos", name: "Arygos", region: "us" },
    { slug: "auchindoun", name: "Auchindoun", region: "us" },
    { slug: "azgalor", name: "Azgalor", region: "us" },
    { slug: "azjolnerub", name: "Azjol-Nerub", region: "us" },
    { slug: "azralon", name: "Azralon", region: "us" },
    { slug: "azshara", name: "Azshara", region: "us" },
    { slug: "azuremyst", name: "Azuremyst", region: "us" },
    { slug: "baelgun", name: "Baelgun", region: "us" },
    { slug: "balnazzar", name: "Balnazzar", region: "us" },
    { slug: "barthilas", name: "Barthilas", region: "us" },
    { slug: "black-dragonflight", name: "Black Dragonflight", region: "us" },
    { slug: "blackhand", name: "Blackhand", region: "us" },
    { slug: "blackrock", name: "Blackrock", region: "us" },
    { slug: "blackwater-raiders", name: "Blackwater Raiders", region: "us" },
    { slug: "blackwing-lair", name: "Blackwing Lair", region: "us" },
    { slug: "blades-edge", name: "Blade's Edge", region: "us" },
    { slug: "bladefist", name: "Bladefist", region: "us" },
    { slug: "bleeding-hollow", name: "Bleeding Hollow", region: "us" },
    { slug: "blood-furnace", name: "Blood Furnace", region: "us" },
    { slug: "bloodhoof", name: "Bloodhoof", region: "us" },
    { slug: "bloodscalp", name: "Bloodscalp", region: "us" },
    { slug: "bonechewer", name: "Bonechewer", region: "us" },
    { slug: "borean-tundra", name: "Borean Tundra", region: "us" },
    { slug: "boulderfist", name: "Boulderfist", region: "us" },
    { slug: "bronzebeard", name: "Bronzebeard", region: "us" },
    { slug: "burning-blade", name: "Burning Blade", region: "us" },
    { slug: "burning-legion", name: "Burning Legion", region: "us" },
    { slug: "caelestrasz", name: "Caelestrasz", region: "us" },
    { slug: "cairne", name: "Cairne", region: "us" },
    { slug: "cenarion-circle", name: "Cenarion Circle", region: "us" },
    { slug: "cenarius", name: "Cenarius", region: "us" },
    { slug: "chogall", name: "Cho'gall", region: "us" },
    { slug: "chromaggus", name: "Chromaggus", region: "us" },
    { slug: "coilfang", name: "Coilfang", region: "us" },
    { slug: "crushridge", name: "Crushridge", region: "us" },
    { slug: "daggerspine", name: "Daggerspine", region: "us" },
    { slug: "dalaran", name: "Dalaran", region: "us" },
    { slug: "dalvengyr", name: "Dalvengyr", region: "us" },
    { slug: "dark-iron", name: "Dark Iron", region: "us" },
    { slug: "darkspear", name: "Darkspear", region: "us" },
    { slug: "darrowmere", name: "Darrowmere", region: "us" },
    { slug: "dathremar", name: "Dath'Remar", region: "us" },
    { slug: "dawnbringer", name: "Dawnbringer", region: "us" },
    { slug: "deathwing", name: "Deathwing", region: "us" },
    { slug: "demon-soul", name: "Demon Soul", region: "us" },
    { slug: "dentarg", name: "Dentarg", region: "us" },
    { slug: "destromath", name: "Destromath", region: "us" },
    { slug: "dethecus", name: "Dethecus", region: "us" },
    { slug: "detheroc", name: "Detheroc", region: "us" },
    { slug: "doomhammer", name: "Doomhammer", region: "us" },
    { slug: "draenor", name: "Draenor", region: "us" },
    { slug: "dragonblight", name: "Dragonblight", region: "us" },
    { slug: "dragonmaw", name: "Dragonmaw", region: "us" },
    { slug: "draktharon", name: "Drak'Tharon", region: "us" },
    { slug: "drakthul", name: "Drak'thul", region: "us" },
    { slug: "draka", name: "Draka", region: "us" },
    { slug: "drakkari", name: "Drakkari", region: "us" },
    { slug: "dreadmaul", name: "Dreadmaul", region: "us" },
    { slug: "drenden", name: "Drenden", region: "us" },
    { slug: "dunemaul", name: "Dunemaul", region: "us" },
    { slug: "durotan", name: "Durotan", region: "us" },
    { slug: "duskwood", name: "Duskwood", region: "us" },
    { slug: "earthen-ring", name: "Earthen Ring", region: "us" },
    { slug: "echo-isles", name: "Echo Isles", region: "us" },
    { slug: "eitrigg", name: "Eitrigg", region: "us" },
    { slug: "eldrethalas", name: "Eldre'Thalas", region: "us" },
    { slug: "elune", name: "Elune", region: "us" },
    { slug: "emerald-dream", name: "Emerald Dream", region: "us" },
    { slug: "eonar", name: "Eonar", region: "us" },
    { slug: "eredar", name: "Eredar", region: "us" },
    { slug: "executus", name: "Executus", region: "us" },
    { slug: "exodar", name: "Exodar", region: "us" },
    { slug: "farstriders", name: "Farstriders", region: "us" },
    { slug: "feathermoon", name: "Feathermoon", region: "us" },
    { slug: "fenris", name: "Fenris", region: "us" },
    { slug: "firetree", name: "Firetree", region: "us" },
    { slug: "fizzcrank", name: "Fizzcrank", region: "us" },
    { slug: "frostmane", name: "Frostmane", region: "us" },
    { slug: "frostmourne", name: "Frostmourne", region: "us" },
    { slug: "frostwolf", name: "Frostwolf", region: "us" },
    { slug: "galakrond", name: "Galakrond", region: "us" },
    { slug: "gallywix", name: "Gallywix", region: "us" },
    { slug: "garithos", name: "Garithos", region: "us" },
    { slug: "garona", name: "Garona", region: "us" },
    { slug: "garrosh", name: "Garrosh", region: "us" },
    { slug: "ghostlands", name: "Ghostlands", region: "us" },
    { slug: "gilneas", name: "Gilneas", region: "us" },
    { slug: "gnomeregan", name: "Gnomeregan", region: "us" },
    { slug: "goldrinn", name: "Goldrinn", region: "us" },
    { slug: "gorefiend", name: "Gorefiend", region: "us" },
    { slug: "gorgonnash", name: "Gorgonnash", region: "us" },
    { slug: "greymane", name: "Greymane", region: "us" },
    { slug: "grizzly-hills", name: "Grizzly Hills", region: "us" },
    { slug: "guldan", name: "Gul'dan", region: "us" },
    { slug: "gundrak", name: "Gundrak", region: "us" },
    { slug: "gurubashi", name: "Gurubashi", region: "us" },
    { slug: "hakkar", name: "Hakkar", region: "us" },
    { slug: "haomarush", name: "Haomarush", region: "us" },
    { slug: "hellscream", name: "Hellscream", region: "us" },
    { slug: "hydraxis", name: "Hydraxis", region: "us" },
    { slug: "hyjal", name: "Hyjal", region: "us" },
    { slug: "icecrown", name: "Icecrown", region: "us" },
    { slug: "illidan", name: "Illidan", region: "us" },
    { slug: "jaedenar", name: "Jaedenar", region: "us" },
    { slug: "jubeithos", name: "Jubei'Thos", region: "us" },
    { slug: "kaelthas", name: "Kael'thas", region: "us" },
    { slug: "kalecgos", name: "Kalecgos", region: "us" },
    { slug: "kargath", name: "Kargath", region: "us" },
    { slug: "kelthuzad", name: "Kel'Thuzad", region: "us" },
    { slug: "khadgar", name: "Khadgar", region: "us" },
    { slug: "khaz-modan", name: "Khaz Modan", region: "us" },
    { slug: "khazgoroth", name: "Khaz'goroth", region: "us" },
    { slug: "kiljaeden", name: "Kil'jaeden", region: "us" },
    { slug: "kilrogg", name: "Kilrogg", region: "us" },
    { slug: "kirin-tor", name: "Kirin Tor", region: "us" },
    { slug: "korgath", name: "Korgath", region: "us" },
    { slug: "korialstrasz", name: "Korialstrasz", region: "us" },
    { slug: "kul-tiras", name: "Kul Tiras", region: "us" },
    { slug: "laughing-skull", name: "Laughing Skull", region: "us" },
    { slug: "lethon", name: "Lethon", region: "us" },
    { slug: "lightbringer", name: "Lightbringer", region: "us" },
    { slug: "lightnings-blade", name: "Lightning's Blade", region: "us" },
    { slug: "lightninghoof", name: "Lightninghoof", region: "us" },
    { slug: "llane", name: "Llane", region: "us" },
    { slug: "lothar", name: "Lothar", region: "us" },
    { slug: "madoran", name: "Madoran", region: "us" },
    { slug: "maelstrom", name: "Maelstrom", region: "us" },
    { slug: "magtheridon", name: "Magtheridon", region: "us" },
    { slug: "maiev", name: "Maiev", region: "us" },
    { slug: "malganis", name: "Mal'Ganis", region: "us" },
    { slug: "malfurion", name: "Malfurion", region: "us" },
    { slug: "malorne", name: "Malorne", region: "us" },
    { slug: "malygos", name: "Malygos", region: "us" },
    { slug: "mannoroth", name: "Mannoroth", region: "us" },
    { slug: "medivh", name: "Medivh", region: "us" },
    { slug: "misha", name: "Misha", region: "us" },
    { slug: "moknathal", name: "Mok'Nathal", region: "us" },
    { slug: "moon-guard", name: "Moon Guard", region: "us" },
    { slug: "moonrunner", name: "Moonrunner", region: "us" },
    { slug: "mugthol", name: "Mug'thol", region: "us" },
    { slug: "muradin", name: "Muradin", region: "us" },
    { slug: "nagrand", name: "Nagrand", region: "us" },
    { slug: "nathrezim", name: "Nathrezim", region: "us" },
    { slug: "nazgrel", name: "Nazgrel", region: "us" },
    { slug: "nazjatar", name: "Nazjatar", region: "us" },
    { slug: "nemesis", name: "Nemesis", region: "us" },
    { slug: "nerzhul", name: "Ner'zhul", region: "us" },
    { slug: "nesingwary", name: "Nesingwary", region: "us" },
    { slug: "nordrassil", name: "Nordrassil", region: "us" },
    { slug: "norgannon", name: "Norgannon", region: "us" },
    { slug: "onyxia", name: "Onyxia", region: "us" },
    { slug: "perenolde", name: "Perenolde", region: "us" },
    { slug: "proudmoore", name: "Proudmoore", region: "us" },
    { slug: "queldorei", name: "Quel'dorei", region: "us" },
    { slug: "quelthalas", name: "Quel'Thalas", region: "us" },
    { slug: "ragnaros", name: "Ragnaros", region: "us" },
    { slug: "ravencrest", name: "Ravencrest", region: "us" },
    { slug: "ravenholdt", name: "Ravenholdt", region: "us" },
    { slug: "rexxar", name: "Rexxar", region: "us" },
    { slug: "rivendare", name: "Rivendare", region: "us" },
    { slug: "runetotem", name: "Runetotem", region: "us" },
    { slug: "sargeras", name: "Sargeras", region: "us" },
    { slug: "saurfang", name: "Saurfang", region: "us" },
    { slug: "scarlet-crusade", name: "Scarlet Crusade", region: "us" },
    { slug: "scilla", name: "Scilla", region: "us" },
    { slug: "senjin", name: "Sen'jin", region: "us" },
    { slug: "sentinels", name: "Sentinels", region: "us" },
    { slug: "shadow-council", name: "Shadow Council", region: "us" },
    { slug: "shadowmoon", name: "Shadowmoon", region: "us" },
    { slug: "shadowsong", name: "Shadowsong", region: "us" },
    { slug: "shandris", name: "Shandris", region: "us" },
    { slug: "shattered-halls", name: "Shattered Halls", region: "us" },
    { slug: "shattered-hand", name: "Shattered Hand", region: "us" },
    { slug: "shuhalo", name: "Shu'halo", region: "us" },
    { slug: "silver-hand", name: "Silver Hand", region: "us" },
    { slug: "silvermoon", name: "Silvermoon", region: "us" },
    { slug: "sisters-of-elune", name: "Sisters of Elune", region: "us" },
    { slug: "skullcrusher", name: "Skullcrusher", region: "us" },
    { slug: "skywall", name: "Skywall", region: "us" },
    { slug: "smolderthorn", name: "Smolderthorn", region: "us" },
    { slug: "spinebreaker", name: "Spinebreaker", region: "us" },
    { slug: "spirestone", name: "Spirestone", region: "us" },
    { slug: "staghelm", name: "Staghelm", region: "us" },
    { slug: "steamwheedle-cartel", name: "Steamwheedle Cartel", region: "us" },
    { slug: "stonemaul", name: "Stonemaul", region: "us" },
    { slug: "stormrage", name: "Stormrage", region: "us" },
    { slug: "stormreaver", name: "Stormreaver", region: "us" },
    { slug: "stormscale", name: "Stormscale", region: "us" },
    { slug: "suramar", name: "Suramar", region: "us" },
    { slug: "tanaris", name: "Tanaris", region: "us" },
    { slug: "terenas", name: "Terenas", region: "us" },
    { slug: "terokkar", name: "Terokkar", region: "us" },
    { slug: "thaurissan", name: "Thaurissan", region: "us" },
    { slug: "the-forgotten-coast", name: "The Forgotten Coast", region: "us" },
    { slug: "the-scryers", name: "The Scryers", region: "us" },
    { slug: "the-underbog", name: "The Underbog", region: "us" },
    { slug: "the-venture-co", name: "The Venture Co", region: "us" },
    { slug: "thorium-brotherhood", name: "Thorium Brotherhood", region: "us" },
    { slug: "thrall", name: "Thrall", region: "us" },
    { slug: "thunderhorn", name: "Thunderhorn", region: "us" },
    { slug: "thunderlord", name: "Thunderlord", region: "us" },
    { slug: "tichondrius", name: "Tichondrius", region: "us" },
    { slug: "tol-barad", name: "Tol Barad", region: "us" },
    { slug: "tortheldrin", name: "Tortheldrin", region: "us" },
    { slug: "trollbane", name: "Trollbane", region: "us" },
    { slug: "turalyon", name: "Turalyon", region: "us" },
    { slug: "twisting-nether", name: "Twisting Nether", region: "us" },
    { slug: "uldaman", name: "Uldaman", region: "us" },
    { slug: "uldum", name: "Uldum", region: "us" },
    { slug: "undermine", name: "Undermine", region: "us" },
    { slug: "ursin", name: "Ursin", region: "us" },
    { slug: "uther", name: "Uther", region: "us" },
    { slug: "vashj", name: "Vashj", region: "us" },
    { slug: "veknilash", name: "Vek'nilash", region: "us" },
    { slug: "velen", name: "Velen", region: "us" },
    { slug: "warsong", name: "Warsong", region: "us" },
    { slug: "whisperwind", name: "Whisperwind", region: "us" },
    { slug: "wildhammer", name: "Wildhammer", region: "us" },
    { slug: "windrunner", name: "Windrunner", region: "us" },
    { slug: "winterhoof", name: "Winterhoof", region: "us" },
    { slug: "wyrmrest-accord", name: "Wyrmrest Accord", region: "us" },
    { slug: "ysera", name: "Ysera", region: "us" },
    { slug: "ysondre", name: "Ysondre", region: "us" },
    { slug: "zangarmarsh", name: "Zangarmarsh", region: "us" },
    { slug: "zuljin", name: "Zul'jin", region: "us" },
    { slug: "zuluhed", name: "Zuluhed", region: "us" },
];
